framework:
  secret: "%env(APP_SECRET)%"
  csrf_protection: true

  # Sessions
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax

  # Localisation
  default_locale: en
  translator:
    default_path: "%kernel.project_dir%/translations"
    fallbacks:
      - en

  # Router
  router:
    utf8: true

  # Profiler (activé par défaut, désactivé en prod via config/packages/prod/framework.yaml)
  profiler: { only_exceptions: false }

  # Cache par défaut
  cache:
    app: cache.adapter.filesystem
    system: cache.adapter.system
