security:
  # https://symfony.com/doc/current/security/experimental_authenticators.html
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#c-hashing-passwords
  password_hashers:
    App\Entity\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      custom_authenticator: App\Security\AppAuthenticator
      lazy: true
      provider: app_user_provider
      logout:
        path: app_logout
        invalidate_session: true

  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

  role_hierarchy:
    ROLE_SUPER: ROLE_ADMIN
    ROLE_ADMIN: ROLE_USER
    ROLE_COORD: ROLE_ADMIN
