doctrine:
  orm:
    auto_generate_proxy_classes: false
    metadata_cache_driver:
      type: pool
      pool: doctrine.metadata_cache_pool
    query_cache_driver:
      type: pool
      pool: doctrine.query_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool
